In [ ]:
pip install numpy

In [ ]:
import numpy as np
print(np.__version__)

2.1.3


In [8]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
import numpy as np
arr=np.zeros((5,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
import numpy as n
arr=n.zeros((10,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
import numpy as np
arr=np.ones((5,7))
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [16]:
import numpy as np
arr=np.full((4,7),9)
print(arr)

[[9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]]


In [18]:
import numpy as np
arr=np.empty((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
import numpy as np
arr=np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [37]:
import numpy as np
arr=np.arange(2,100)
print(arr)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]


In [40]:
import numpy as np
Even=np.arange(1,100,2)
print(Even)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [41]:
import numpy as np
Even=np.arange(2,100,2)
print(Even)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [46]:
import numpy as np
arr=np.linspace(1,20,7)
print(arr)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [48]:
import numpy as np
arr=np.random.randn(10)
print(arr)

[-1.47939646  1.84314376  1.49736977 -0.03031019  1.17533332 -1.09992181
 -0.20263906 -0.90830409  1.91300509  0.31171467]


In [49]:
import numpy as np
arr=np.random.rand(10)
print(arr)

[0.44306695 0.69574896 0.75367062 0.00936919 0.84850905 0.66397937
 0.84725945 0.48258074 0.74768753 0.54806322]


In [77]:
import numpy as np
arr=np.random.randint(10)
print(arr)

4


In [103]:
import numpy as np
colours=["red","green","pink","black","yellow","orange","black"]
print(np.random.choice(colours,2))

['pink' 'orange']


In [104]:
import numpy as np
arr=np.array([1,2,3])
new=arr.copy()
new[1]=100
print("Array value is :",arr)
print("Copy value is :",new)

Array value is : [1 2 3]
Copy value is : [  1 100   3]


In [105]:
import numpy as np
arr=np.array([1,2,3])
new=arr.view()
new[1]=100
print("Array value is :",arr)
print("View value is :",new)

Array value is : [  1 100   3]
View value is : [  1 100   3]


In [107]:
import numpy as np
arr=np.array([5,10,15,20,25,30])
arr +=20
print("Updated array value is :",arr)

Updated array value is : [25 30 35 40 45 50]


In [115]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.add(A,B))

[ 7  9 11 13 15]


In [118]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.subtract(A,B))

[-5 -5 -5 -5 -5]


In [116]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.divide(A,B))

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [117]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.multiply(A,B))

[ 6 14 24 36 50]


In [121]:
import numpy as np
A=np.array([1,2,3,4,5])
B=np.array([6,7,8,9,10])
print(np.dot(A,B))

130


In [135]:
import numpy as np
Arr=np.array([1,2,3,4,5,6,7,8,9])
print(sum(Arr))
print(max(Arr))
print(min(Arr))
print(np.std(Arr))
print(np.square(Arr))
print(np.sqrt(Arr))


45
9
1
2.581988897471611
[ 1  4  9 16 25 36 49 64 81]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [138]:
import numpy as np
arr=np.array([9,4,7,3,8,9,4,1,11,141,34])
print(np.sort(arr))

[  1   3   4   4   7   8   9   9  11  34 141]


In [139]:
import numpy as np
arr=np.array([1,2,3,4,1,2,3,4,9,8,5])
print(np.unique(arr))

[1 2 3 4 5 8 9]


In [148]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr.shape)
print(arr.size)
print(arr.itemsize)
print(arr.ndim)
print(arr.dtype)

(9,)
9
8
1
int64


In [162]:
import numpy as np
arr=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr.shape)
print(arr.ndim)
print(arr[0,1])
print(arr[1,1])
print(arr[:,2])
print(arr[0])
print(arr.reshape)

(2, 5)
2
2
2
[3 3]
[1 2 3 4 5]
<built-in method reshape of numpy.ndarray object at 0x78dcdebeddd0>


In [167]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
new=arr.reshape(5,3)
print(new)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
